site_name: ROSRider Documentation
pages:
- Readme: README.md
- Getting Started: START.md
- Installing the ROSRider Software: SOFTWARE.md
- Parameters: PARAMS.md
- Launching ROSRider: LAUNCH.md
- Services: SERVICES.md
theme: readthedocs
