site_name: ROSRider Documentation
pages:
- Readme: README.md
- Getting Started: 01_START.md
- Installing the ROSRider Software: 02_SOFTWARE.md
- Parameters Explained: 03_PARAMS.md
- Launching ROSRider: 04_LAUNCH.md
theme: readthedocs
