site_name: ROSRider Documentation
pages:
- Readme: README.md
- Prerequisites: PRE.md
- Getting Started: START.md
- Installing ROSRider Software: SOFTWARE.md
- Parameters: PARAMS.md
- Launching ROSRider: LAUNCH.md
- Subscribers and Publishers:
    - 'Provided by ROSRider': NATIVE.md
    - 'Provided by ROS': TOPICS.md
- Services: SERVICES.md
- Diagnostics: DIAGS.md
- Examples: EXAMPLES.md
- EKF: EKF.md
- Gazebo: GAZEBO.md
- Calibration: CALIBRATION.md
- Procedures: PROCEDURES.md
- Network: NETWORK.md
- About: ABOUT.md
theme: readthedocs
